#!/usr/bin/env python
from socket import socket, AF_INET, SOCK_STREAM
import sys
import select

if __name__ == '__main__':
    listen_port = sys.argv[1]
    fake_ip = sys.argv[2]
    server_ip = sys.argv[3]
    poll = []
    # start listening to listed port.
    proxySocket = socket(AF_INET, SOCK_STREAM)
    proxySocket.bind(('', int(listen_port)))
    proxySocket.listen(1)
    print('The proxy is ready to receive')
    while True:
        # start receiving the first client.
        clientSocket, _ = proxySocket.accept()
        poll.append(clientSocket)
        while len(poll):
            print('new client come in')
            # try to connect to server
            try:
                serverSocket = socket(AF_INET, SOCK_STREAM) 
                serverSocket.connect((server_ip, 8080))
            except:
                pass 
            currentSocket = poll.pop(0)
            try:
                while True:
                    inputs = [currentSocket, serverSocket]
                    ready_to_read, ready_to_write, in_error = select.select(inputs, [], inputs, 1)
                    print(inputs)
                    if len(inputs) == 0:
                        break
                    sentence = currentSocket.recv(1024)
                    serverSocket.send(sentence)
                    response = serverSocket.recv(1024)
                    currentSocket.send(response)
            except Exception as e:
                print(e)
                currentSocket.close()
                serverSocket.close()
                print('current connection down')
    #proxySocket.close()
