#!/usr/bin/env python
from socket import socket, AF_INET, SOCK_STREAM
import time

import sys
if __name__ == '__main__':
    print(sys.argv)
    listen_port = sys.argv[1]
    fake_ip = sys.argv[2]
    server_ip = sys.argv[3]
    #listen_port = "8080"
    #fake_ip = "127.0.0.1"
    #server_ip = "127.0.0.1"
    try:
        proxySocket = socket(AF_INET, SOCK_STREAM)
        proxySocket.bind(('', int(listen_port)))
        proxySocket.listen(1)
        print('The proxy is ready to receive')
    except:
        print('unable to initialize proxy!')
        sys.exit(2)
    while True:
        try:
            clientSocket, addr = proxySocket.accept()
            sentence = clientSocket.recv(1024)
            print('client detected! data!')
            serverSocket = socket(AF_INET, SOCK_STREAM)
            serverSocket.connect((server_ip, 8080))
            if len(sentence) > 0:
                serverSocket.sendall(sentence)
            response = serverSocket.recv(1024)
            if len(response) > 0:
                clientSocket.send(response)
            #proxy_server(server_ip, 8080 ,clientSocket,addr,sentence)
        except Exception as e:
            print(e)
            proxySocket.close()
            print('current client down.')
            #sys.exit(1)

